[package]
name = "hvm-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
extend = "1.2.0"
tempfile = "3.10.1"
wait-timeout = "0.2.0"
